### ISSUE TITLE
Drag and Drop form builder in Fred

### ISSUE THREAD

**Issue by pixelstuff** [modxcms/fred#102]
It would be nice if Fred had a form element that opened up a drag and drop form editor such as the jQuery form builder plugin https://formbuilder.online/ or something similar.

**Comment by rthrash** [comment]
You can create form Elements, put them in a form category, and use Fred to build forms today. Is there something else you had in mind?

**Comment by digitalpenguin** [comment]
Yeah building forms with Fred (drag and drop) works really well. I put one together the other day ;)

**Comment by rthrash** [comment]
You can even probably style JS vallidation error messages using data-fred-render=false on a DIV and then binding the value to the error message in the attribute/div (or however it's handled in your form fields).

@pixelstuff are you looking for an out of the box example, or just the capability to create forms with Fred?

**Comment by sjmclean24** [comment]
@rthrash @digitalpenguin it would be a good idea to look into the idea of existing Extras hooking up/extending the Fred functionality. I see this as a more feasible solution for the following reasons:

- Fred itself not becoming bloated;
- Allowing the Development Team to focus on more Core Functionality rather then specific use cases (which I believe is not feasible, especially given it's a Free Extra);
- Reusability of code;
- It will allow a 'Best of Breed' approach, where developers who have already acquired the functional and user knowledge of processes, in this case building contact forms, can re-use that to extend into Fred rather than having the MODX Team use production time to relearn such fundamentals.

Of course, there is always the limitation that this totally depends on the Extra developers to extend its functionality to Fred :)

But in the meantime, I believe there is already a middle ground where you can build through the MODX Manager and then call it in Fred using a snippet?

**Comment by pixelstuff** [comment]
So far I haven't found any add-on or snippet in MODx that is as easy as using Jotform or Google Forms. I have a customer who builds forms regularly for events and then links out to one of those services. They don't do it in MODx because it's either too slow or complicated.

**Comment by sjmclean24** [comment]
@pixelstuff have you checked Formalicious (https://www.modmore.com/formalicious/)? Of course, when solutioning it is ok to use external systems which works well for the business case :)

**Comment by rthrash** [comment]
@pixelstuff there is not any logic to support limiting dropzones or validation yet. It's on the radar, along will full robust ACL support, but don't expect that soon.

**Comment by digitalpenguin** [comment]
Wow yeah limiting dropzones would be a fantastic feature.
