### ISSUE TITLE
Feature Request: Repeatable fields with pagination

### ISSUE THREAD

**Issue by muzzwood** [modxcms/fred#19]
I'm not sure if there's currently a way to do this, but if not:

Allow for a repeatable field input type directly in Fred. For clients who want to upload images in a gallery for example that could be paginated. The block itself could have a getPage/pdoPage call doing the pagination.

The backend of this could perhaps be achieved with a couple of db tables. One for a "gallery" and one for "gallery-item". The main thing needed I believe would be the interface for it - this would remove the need for clients to be swapping between the manager and web contexts just to add images.

**Comment by digitalpenguin** [comment]
I think a gallery may have been the wrong example to use.
The idea is for a listing/index page managed via the Fred interface. It could be a listing of blog posts, media items, news posts, products etc.
Paging via JavaScript would of course get unwieldy if there are too many items so that's why I mentioned the database tables. 
I understand this would be a difficult thing to implement properly but it would be absolutely amazing if it were done! :)

**Comment by theboxer** [comment]
I think I still don't follow the request. You can use getResources & getPage together with element settings (to specify things like page size, parent resource, tpl) to get a server side generated list of blog posts, or just resources. You'd need to set `remote` option to `true` for these elements. This is for listing them, for creating them, you'd have to either create them from manager, or if they are fred resources, create a new fred page under correct parent.

**Comment by digitalpenguin** [comment]
You're right, I've done it that way before and it works nicely, the only problem is it requires switching back and forth between the Fred interface and the manager. (Usually there will be image TVs etc on each item)
Allowing a user to drag a "preview" item into a list from the Fred sidebar would enable them to set images, text etc. without using TVs.
