### ISSUE TITLE
AjaxForm seems to create issues when used with FRED

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [modxcms/fred#290]
When using a AjaxForm and editing in FRED I see this in the console:

`Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-3.1.1.min.js:2 jQuery.Deferred exception: Cannot read property 'defaults' of undefined TypeError: Cannot read property 'defaults' of undefined
    at HTMLDocument.<anonymous> (/assets/components/ajaxform/js/default.js:12:22)
    at j (/assets/themes/HireFirst/js/jquery-3.1.1.min.js:2:29948)
    at k (/assets/themes/HireFirst/js/jquery-3.1.1.min.js:2:30262) undefined`

**Comment by rthrash** [comment]
Hi Menno, what’s the use case you’re trying to achieve? We’ll look into this and see if we can figure out the best way to get it sorted out ahead of the 1.1 final release. Thanks!

**Comment by DESIGNfromWITHIN** [comment]
Well just use AjaxForm, if you do in any way the JS added by AjaxForm give errors in the FRED edit view (it works outside of it)

**Comment by theboxer** [comment]
Could you provide some more details and a use case (element markup, options if used, chunks if used, snippets if used, etc.)? I never used AjaxForm (or even know it exists).

**Comment by theboxer** [comment]
Not possible due to how ajaxform injects assets to head from snippet.

**Comment by ivan-kuzin** [comment]
And what we must do? Use ajax forms with Fred its impossible?

**Comment by matdave** [comment]
@ivan-kuzin, 

Fred works on the frontend without re-rendering a page. The Ajax Form snippet currently injects the required CSS/JS on the page in the head using the MODX parser. There's currently no way for a snippet to manipulate a page and add scripts during the editor render process since the page is not re-rendered or reprocessed during frontend manipulation.

It is possible to create ajax forms without this snippet, it is just how this particular snippet/plugin is built that prevents it from working with fred.
