### ISSUE TITLE
New option set folder type - How to use?

### ISSUE THREAD

**Issue by JANogueira** [modxcms/fred#305]
Hi,

I am trying to use the new folder type option:
https://github.com/modxcms/fred/blob/master/docs/themer/options/settings.md#folder

Is there any native Fred controller to get all files inside a folder?
This is my optionset:
```
{
  "settings": [
    {
      "name": "gallery_detail_folder",
      "label": "Gallery Folder",
      "type": "folder",
      "mediaSource": "Patraomor",
      "value": ""
    },
    {
      "fred-import": "panel_common_simple"
    }
  ]
}
```

and the twig call:
```
{% for file in gallery_detail_folder %}
	{{ file }}<br>
{% endfor %}
```

But seems that no controller exists to go over all files on a folder.
Do you have any use case that can be shared on the documentation concerning this new field type?

Thanks in advancd

**Comment by theboxer** [comment]
The `folder` type is not meant to show files from a specific folder, but for the user to be able to select a folder instead of file. It also has an option `showOnlyFolders` to show only folders in the elFinder.

If you want to be able to show files in a specific folder, you have to create a media source for that.
