### ISSUE TITLE
Fred brake site template on frontend

### ISSUE THREAD

**Issue by NDruce** [modxcms/fred#350]
Before:
![image](https://user-images.githubusercontent.com/33526036/77460489-31ab5480-6e12-11ea-95a6-9abb3551b3d0.png)

After assigning Fred to template:
![image](https://user-images.githubusercontent.com/33526036/77460580-543d6d80-6e12-11ea-931b-415041546fde.png)

I was expected this problem even 1 year ago, but still nothing fixed(

**Comment by matdave** [comment]
The screenshot doesn't really tell enough to know which parts of the page are editable and which parts of the page are just part of the template. I am guessing that your CSS requires some nesting precision on classes that is getting blocked by element wrappers when Fred is enabled. 

The Fred block class might solve these issues (https://modxcms.github.io/fred/themer/elements/attributes/#data-fred-block-class) 

Otherwise you will need to inspect the code and tell us precisely what is "breaking". This looks like it is just improperly targeted CSS though.
