### ISSUE TITLE
Make sidebar actions consistent

### ISSUE THREAD

**Issue by qodo** [modxcms/fred#363]
When using the sidebar I have to click on "Blueprints" or "Elements" for the menu to open but then I have to hover the categories for them to show.

It would be great if these are consistent actions. My preference is click to open the menu item as it makes it easier to see what's happening as rolling over the items you get a flash of the submenu as you move your mouse.

Thanks,

**Comment by rthrash** [comment]
@matdave I think it makes the most sense to keep things consistent with a click to open.

**Comment by matdave** [comment]
The reason for the top level elements requiring a click is because it requires a request, and would slow down you initial operations when you hover if they each opened. The reason for the elements load on hover is because it increases the workflow. Originally, each action required a click (and still do as a fallback) but the hover was added to speed up searching for elements.

**Comment by rthrash** [comment]
@qodo does that make sense? It still works on click so you could consider this progressive enhancement.

**Comment by rthrash** [comment]
@qodo … or you could use it in Safari, as it works exactly that way there. (just kidding) … in any case closing this out as the fallback works.

**Comment by qodo** [comment]
Thanks for the update on this. My preference would be that all opening of menus happens on click. Not tried this on a tablet but a hover action on touch devices might not work as expected?
