### ISSUE TITLE
data-fred-target doesn't store content

### ISSUE THREAD

**Issue by reikotec** [modxcms/fred#6]
I'm defining with data-fred-target the Resource field to store content. But it doesn't work.

`<h1 data-fred-name="title" data-fred-target="pagetitle" contenteditable="true">[[*pagetitle]]</h1>`

After Saving and Refreshing the page the old pagetitle is shown.
Same Problem with the complete Content. I can edit the content with Fred I dropped in the dropzone, and it is safed. But when I open the page logged out, as an anonymous user, no content is diplayed.

`<div data-fred-dropzone="main" data-fred-target="content">[[*content]]</div>`

With Fred:
![grafik](https://user-images.githubusercontent.com/41062056/42514354-81308628-8459-11e8-90fe-99d45baa73fa.png)

Sample Element Chunk:
`<div data-fred-name="rte-content" contenteditable="true" data-fred-rte="true" date-fred-render="true">Default Content</div>`

Public Frontend as a non-user:
![grafik](https://user-images.githubusercontent.com/41062056/42514437-b907be22-8459-11e8-9447-6928aeeac161.png)

Is this a bug, oder am I doing something wrong?

**Comment by theboxer** [comment]
Hello,

first thing I spot is, that you named your root dropzone `main`, which is unfortunately not yet documented. You have to name it `content` -> `<div data-fred-dropzone="content">[[*content]]</div>`

Otherwise it won't save at all (this rule is only for the dropzone in the template, dropzones in elements can be named however you want).

Next thing, `data-fred-target` can be used only for few resource fields and content is not one of them, as it's used for generated content from the `content` dropzone. Also `data-fred-target` can be used only on `contenteditable` items, not on whole dropzones.

List of available targets:
- pagetitle
- longtitle
- description
- introtext
- menutitle
- alias

Please let me know if it resolved the issue you are having.

**Comment by reikotec** [comment]
Wow thank you for your fast answer, it solved my issue!

**I changed my code as following:**

In the Template
`<div data-fred-dropzone="content">[[*content]]</div>`

And I created a new Chunk / Element for dropping named Pagetitle
`<h1 data-fred-name="title" data-fred-target="pagetitle" contenteditable="true">[[*pagetitle]]</h1>`

Now it works very fine! 
Thank you a lot!
